---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  labels:
    name: bggdb-deploy
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
        name: bggdb-po
    spec:
      containers: # has one container
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports: # container exposed port
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
      name: bggdb-po
  ports:
  - port: 3306 #service port where external will hit
    targetPort: 3306 #container port where service will hit
---